#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	nsd_hits
	nsd_memory
	nsd_by_type
	nsd_by_class
	nsd_by_opcode
	nsd_by_rcode
	nsd_zones
"

# Exit if any commands fail
set -o errexit

echo "* Workaround for cron script to check logs"
chmod 755 /opt/core/bin/check-log

echo "* Configuring image specific packages.";
git clone http://github.com/bluemaex/generate-zonefile.git /opt/blmx/generate-zonefile
cd /opt/blmx/generate-zonefile && npm install

echo "* Create nsd database folder and setup permissions"
mkdir -p /var/nsd
chown nsd:nsd /var/nsd

echo "* Change permissions for nsd config folder"
mkdir -p /opt/local/etc/nsd/zones
chown -R nsd:nsd /opt/local/etc/nsd

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
